/* A list of monster names in English, from the original monst.c */

#define	NAM_GIANT_ANT	"giant ant"
#define	NAM_KILLER_BEE	"killer bee"
#define	NAM_SOLDIER_ANT	"soldier ant"
#define	NAM_FIRE_ANT	"fire ant"
#define	NAM_GIANT_BEETLE	"giant beetle"
#define	NAM_QUEEN_BEE	"queen bee"
#define	NAM_ACID_BLOB	"acid blob"
#define	NAM_QUIVERING_BLOB	"quivering blob"
#define	NAM_GELATINOUS_CUBE	"gelatinous cube"
#define	NAM_CHICKATRICE	"chickatrice"
#define	NAM_COCKATRICE	"cockatrice"
#define	NAM_PYROLISK	"pyrolisk"
#define	NAM_JACKAL	"jackal"
#define	NAM_FOX	"fox"
#define	NAM_COYOTE	"coyote"
#define	NAM_WEREJACKAL	"werejackal"
#define	NAM_LITTLE_DOG	"little dog"
#define	NAM_DOG	"dog"
#define	NAM_LARGE_DOG	"large dog"
#define	NAM_DINGO	"dingo"
#define	NAM_WOLF	"wolf"
#define	NAM_WEREWOLF	"werewolf"
#define	NAM_WARG	"warg"
#define	NAM_WINTER_WOLF_CUB	"winter wolf cub"
#define	NAM_WINTER_WOLF	"winter wolf"
#define	NAM_HELL_HOUND_PUP	"hell hound pup"
#define	NAM_HELL_HOUND	"hell hound"
#define	NAM_CERBERUS	"Cerberus"
#define	NAM_GAS_SPORE	"gas spore"
#define	NAM_FLOATING_EYE	"floating eye"
#define	NAM_FREEZING_SPHERE	"freezing sphere"
#define	NAM_FLAMING_SPHERE	"flaming sphere"
#define	NAM_SHOCKING_SPHERE	"shocking sphere"
#define	NAM_BEHOLDER	"beholder"
#define	NAM_KITTEN	"kitten"
#define	NAM_HOUSECAT	"housecat"
#define	NAM_JAGUAR	"jaguar"
#define	NAM_LYNX	"lynx"
#define	NAM_PANTHER	"panther"
#define	NAM_LARGE_CAT	"large cat"
#define	NAM_TIGER	"tiger"
#define	NAM_GREMLIN	"gremlin"
#define	NAM_GARGOYLE	"gargoyle"
#define	NAM_WINGED_GARGOYLE	"winged gargoyle"
#define	NAM_HOBBIT	"hobbit"
#define	NAM_DWARF	"dwarf"
#define	NAM_BUGBEAR	"bugbear"
#define	NAM_DWARF_LORD	"dwarf lord"
#define	NAM_DWARF_KING	"dwarf king"
#define	NAM_MIND_FLAYER	"mind flayer"
#define	NAM_MASTER_MIND_FLAYER	"master mind flayer"
#define	NAM_MANES	"manes"
#define	NAM_HOMUNCULUS	"homunculus"
#define	NAM_IMP	"imp"
#define	NAM_LEMURE	"lemure"
#define	NAM_QUASIT	"quasit"
#define	NAM_TENGU	"tengu"
#define	NAM_BLUE_JELLY	"blue jelly"
#define	NAM_SPOTTED_JELLY	"spotted jelly"
#define	NAM_OCHRE_JELLY	"ochre jelly"
#define	NAM_KOBOLD	"kobold"
#define	NAM_LARGE_KOBOLD	"large kobold"
#define	NAM_KOBOLD_LORD	"kobold lord"
#define	NAM_KOBOLD_SHAMAN	"kobold shaman"
#define	NAM_LEPRECHAUN	"leprechaun"
#define	NAM_SMALL_MIMIC	"small mimic"
#define	NAM_LARGE_MIMIC	"large mimic"
#define	NAM_GIANT_MIMIC	"giant mimic"
#define	NAM_WOOD_NYMPH	"wood nymph"
#define	NAM_WATER_NYMPH	"water nymph"
#define	NAM_MOUNTAIN_NYMPH	"mountain nymph"
#define	NAM_GOBLIN	"goblin"
#define	NAM_HOBGOBLIN	"hobgoblin"
#define	NAM_ORC	"orc"
#define	NAM_HILL_ORC	"hill orc"
#define	NAM_MORDOR_ORC	"Mordor orc"
#define	NAM_URUK_HAI	"Uruk-hai"
#define	NAM_ORC_SHAMAN	"orc shaman"
#define	NAM_ORC_CAPTAIN	"orc-captain"
#define	NAM_ROCK_PIERCER	"rock piercer"
#define	NAM_IRON_PIERCER	"iron piercer"
#define	NAM_GLASS_PIERCER	"glass piercer"
#define	NAM_ROTHE	"rothe"
#define	NAM_MUMAK	"mumak"
#define	NAM_LEOCROTTA	"leocrotta"
#define	NAM_WUMPUS	"wumpus"
#define	NAM_TITANOTHERE	"titanothere"
#define	NAM_BALUCHITHERIUM	"baluchitherium"
#define	NAM_MASTODON	"mastodon"
#define	NAM_SEWER_RAT	"sewer rat"
#define	NAM_GIANT_RAT	"giant rat"
#define	NAM_RABID_RAT	"rabid rat"
#define	NAM_WERERAT	"wererat"
#define	NAM_ROCK_MOLE	"rock mole"
#define	NAM_WOODCHUCK	"woodchuck"
#define	NAM_CAVE_SPIDER	"cave spider"
#define	NAM_CENTIPEDE	"centipede"
#define	NAM_GIANT_SPIDER	"giant spider"
#define	NAM_SCORPION	"scorpion"
#define	NAM_LURKER_ABOVE	"lurker above"
#define	NAM_TRAPPER	"trapper"
#define	NAM_WHITE_UNICORN	"white unicorn"
#define	NAM_GRAY_UNICORN	"gray unicorn"
#define	NAM_BLACK_UNICORN	"black unicorn"
#define	NAM_PONY	"pony"
#define	NAM_HORSE	"horse"
#define	NAM_WARHORSE	"warhorse"
#define	NAM_FOG_CLOUD	"fog cloud"
#define	NAM_DUST_VORTEX	"dust vortex"
#define	NAM_ICE_VORTEX	"ice vortex"
#define	NAM_ENERGY_VORTEX	"energy vortex"
#define	NAM_STEAM_VORTEX	"steam vortex"
#define	NAM_FIRE_VORTEX	"fire vortex"
#define	NAM_BABY_LONG_WORM	"baby long worm"
#define	NAM_BABY_PURPLE_WORM	"baby purple worm"
#define	NAM_LONG_WORM	"long worm"
#define	NAM_PURPLE_WORM	"purple worm"
#define	NAM_GRID_BUG	"grid bug"
#define	NAM_XAN	"xan"
#define	NAM_YELLOW_LIGHT	"yellow light"
#define	NAM_BLACK_LIGHT	"black light"
#define	NAM_ZRUTY	"zruty"
#define	NAM_COUATL	"couatl"
#define	NAM_ALEAX	"Aleax"
#define	NAM_ANGEL	"Angel"
#define	NAM_KI_RIN	"ki-rin"
#define	NAM_ARCHON	"Archon"
#define	NAM_BAT	"bat"
#define	NAM_GIANT_BAT	"giant bat"
#define	NAM_RAVEN	"raven"
#define	NAM_VAMPIRE_BAT	"vampire bat"
#define	NAM_PLAINS_CENTAUR	"plains centaur"
#define	NAM_FOREST_CENTAUR	"forest centaur"
#define	NAM_MOUNTAIN_CENTAUR	"mountain centaur"
#define	NAM_BABY_GRAY_DRAGON	"baby gray dragon"
#define	NAM_BABY_SILVER_DRAGON	"baby silver dragon"
#define	NAM_BABY_SHIMMERING_DRAGON	"baby shimmering dragon"
#define	NAM_BABY_RED_DRAGON	"baby red dragon"
#define	NAM_BABY_WHITE_DRAGON	"baby white dragon"
#define	NAM_BABY_ORANGE_DRAGON	"baby orange dragon"
#define	NAM_BABY_BLACK_DRAGON	"baby black dragon"
#define	NAM_BABY_BLUE_DRAGON	"baby blue dragon"
#define	NAM_BABY_GREEN_DRAGON	"baby green dragon"
#define	NAM_BABY_YELLOW_DRAGON	"baby yellow dragon"
#define	NAM_GRAY_DRAGON	"gray dragon"
#define	NAM_SILVER_DRAGON	"silver dragon"
#define	NAM_SHIMMERING_DRAGON	"shimmering dragon"
#define	NAM_RED_DRAGON	"red dragon"
#define	NAM_WHITE_DRAGON	"white dragon"
#define	NAM_ORANGE_DRAGON	"orange dragon"
#define	NAM_BLACK_DRAGON	"black dragon"
#define	NAM_BLUE_DRAGON	"blue dragon"
#define	NAM_GREEN_DRAGON	"green dragon"
#define	NAM_YELLOW_DRAGON	"yellow dragon"
#define	NAM_STALKER	"stalker"
#define	NAM_AIR_ELEMENTAL	"air elemental"
#define	NAM_FIRE_ELEMENTAL	"fire elemental"
#define	NAM_EARTH_ELEMENTAL	"earth elemental"
#define	NAM_WATER_ELEMENTAL	"water elemental"
#define	NAM_LICHEN	"lichen"
#define	NAM_BROWN_MOLD	"brown mold"
#define	NAM_YELLOW_MOLD	"yellow mold"
#define	NAM_GREEN_MOLD	"green mold"
#define	NAM_RED_MOLD	"red mold"
#define	NAM_SHRIEKER	"shrieker"
#define	NAM_VIOLET_FUNGUS	"violet fungus"
#define	NAM_GNOME	"gnome"
#define	NAM_GNOME_LORD	"gnome lord"
#define	NAM_GNOMISH_WIZARD	"gnomish wizard"
#define	NAM_GNOME_KING	"gnome king"
#define	NAM_GIANT	"giant"
#define	NAM_STONE_GIANT	"stone giant"
#define	NAM_HILL_GIANT	"hill giant"
#define	NAM_FIRE_GIANT	"fire giant"
#define	NAM_FROST_GIANT	"frost giant"
#define	NAM_STORM_GIANT	"storm giant"
#define	NAM_ETTIN	"ettin"
#define	NAM_TITAN	"titan"
#define	NAM_MINOTAUR	"minotaur"
#define	NAM_JABBERWOCK	"jabberwock"
#define	NAM_VORPAL_JABBERWOCK	"vorpal jabberwock"
#define	NAM_KEYSTONE_KOP	"Keystone Kop"
#define	NAM_KOP_SERGEANT	"Kop Sergeant"
#define	NAM_KOP_LIEUTENANT	"Kop Lieutenant"
#define	NAM_KOP_KAPTAIN	"Kop Kaptain"
#define	NAM_LICH	"lich"
#define	NAM_DEMILICH	"demilich"
#define	NAM_MASTER_LICH	"master lich"
#define	NAM_ARCH_LICH	"arch-lich"
#define	NAM_KOBOLD_MUMMY	"kobold mummy"
#define	NAM_GNOME_MUMMY	"gnome mummy"
#define	NAM_ORC_MUMMY	"orc mummy"
#define	NAM_DWARF_MUMMY	"dwarf mummy"
#define	NAM_ELF_MUMMY	"elf mummy"
#define	NAM_HUMAN_MUMMY	"human mummy"
#define	NAM_ETTIN_MUMMY	"ettin mummy"
#define	NAM_GIANT_MUMMY	"giant mummy"
#define	NAM_RED_NAGA_HATCHLING	"red naga hatchling"
#define	NAM_BLACK_NAGA_HATCHLING	"black naga hatchling"
#define	NAM_GOLDEN_NAGA_HATCHLING	"golden naga hatchling"
#define	NAM_GUARDIAN_NAGA_HATCHLING	"guardian naga hatchling"
#define	NAM_RED_NAGA	"red naga"
#define	NAM_BLACK_NAGA	"black naga"
#define	NAM_GOLDEN_NAGA	"golden naga"
#define	NAM_GUARDIAN_NAGA	"guardian naga"
#define	NAM_OGRE	"ogre"
#define	NAM_OGRE_LORD	"ogre lord"
#define	NAM_OGRE_KING	"ogre king"
#define	NAM_GRAY_OOZE	"gray ooze"
#define	NAM_BROWN_PUDDING	"brown pudding"
#define	NAM_BLACK_PUDDING	"black pudding"
#define	NAM_GREEN_SLIME	"green slime"
#define	NAM_QUANTUM_MECHANIC	"quantum mechanic"
#define	NAM_RUST_MONSTER	"rust monster"
#define	NAM_DISENCHANTER	"disenchanter"
#define	NAM_GARTER_SNAKE	"garter snake"
#define	NAM_SNAKE	"snake"
#define	NAM_WATER_MOCCASIN	"water moccasin"
#define	NAM_PIT_VIPER	"pit viper"
#define	NAM_PYTHON	"python"
#define	NAM_COBRA	"cobra"
#define	NAM_TROLL	"troll"
#define	NAM_ICE_TROLL	"ice troll"
#define	NAM_ROCK_TROLL	"rock troll"
#define	NAM_WATER_TROLL	"water troll"
#define	NAM_OLOG_HAI	"Olog-hai"
#define	NAM_UMBER_HULK	"umber hulk"
#define	NAM_VAMPIRE	"vampire"
#define	NAM_VAMPIRE_LORD	"vampire lord"
#define	NAM_VAMPIRE_MAGE	"vampire mage"
#define	NAM_VLAD_THE_IMPALER	"Vlad the Impaler"
#define	NAM_BARROW_WIGHT	"barrow wight"
#define	NAM_WRAITH	"wraith"
#define	NAM_NAZGUL	"Nazgul"
#define	NAM_XORN	"xorn"
#define	NAM_MONKEY	"monkey"
#define	NAM_APE	"ape"
#define	NAM_OWLBEAR	"owlbear"
#define	NAM_YETI	"yeti"
#define	NAM_CARNIVOROUS_APE	"carnivorous ape"
#define	NAM_SASQUATCH	"sasquatch"
#define	NAM_KOBOLD_ZOMBIE	"kobold zombie"
#define	NAM_GNOME_ZOMBIE	"gnome zombie"
#define	NAM_ORC_ZOMBIE	"orc zombie"
#define	NAM_DWARF_ZOMBIE	"dwarf zombie"
#define	NAM_ELF_ZOMBIE	"elf zombie"
#define	NAM_HUMAN_ZOMBIE	"human zombie"
#define	NAM_ETTIN_ZOMBIE	"ettin zombie"
#define	NAM_GIANT_ZOMBIE	"giant zombie"
#define	NAM_GHOUL	"ghoul"
#define	NAM_SKELETON	"skeleton"
#define	NAM_STRAW_GOLEM	"straw golem"
#define	NAM_PAPER_GOLEM	"paper golem"
#define	NAM_ROPE_GOLEM	"rope golem"
#define	NAM_GOLD_GOLEM	"gold golem"
#define	NAM_LEATHER_GOLEM	"leather golem"
#define	NAM_WOOD_GOLEM	"wood golem"
#define	NAM_FLESH_GOLEM	"flesh golem"
#define	NAM_CLAY_GOLEM	"clay golem"
#define	NAM_STONE_GOLEM	"stone golem"
#define	NAM_GLASS_GOLEM	"glass golem"
#define	NAM_IRON_GOLEM	"iron golem"
#define	NAM_HUMAN	"human"
#define	NAM_ELF	"elf"
#define	NAM_WOODLAND_ELF	"Woodland-elf"
#define	NAM_GREEN_ELF	"Green-elf"
#define	NAM_GREY_ELF	"Grey-elf"
#define	NAM_ELF_LORD	"elf-lord"
#define	NAM_ELVENKING	"Elvenking"
#define	NAM_DOPPELGANGER	"doppelganger"
#define	NAM_NURSE	"nurse"
#define	NAM_SHOPKEEPER	"shopkeeper"
#define	NAM_GUARD	"guard"
#define	NAM_PRISONER	"prisoner"
#define	NAM_ORACLE	"Oracle"
#define	NAM_ALIGNED_PRIEST	"aligned priest"
#define	NAM_HIGH_PRIEST	"high priest"
#define	NAM_SOLDIER	"soldier"
#define	NAM_SERGEANT	"sergeant"
#define	NAM_LIEUTENANT	"lieutenant"
#define	NAM_CAPTAIN	"captain"
#define	NAM_WATCHMAN	"watchman"
#define	NAM_WATCH_CAPTAIN	"watch captain"
#define	NAM_MEDUSA	"Medusa"
#define	NAM_WIZARD_OF_YENDOR	"Wizard of Yendor"
#define	NAM_CROESUS	"Croesus"
#define	NAM_CHARON	"Charon"
#define	NAM_GHOST	"ghost"
#define	NAM_SHADE	"shade"
#define	NAM_WATER_DEMON	"water demon"
#define	NAM_HORNED_DEVIL	"horned devil"
#define	NAM_SUCCUBUS	"succubus"
#define	NAM_INCUBUS	"incubus"
#define	NAM_ERINYS	"erinys"
#define	NAM_BARBED_DEVIL	"barbed devil"
#define	NAM_MARILITH	"marilith"
#define	NAM_VROCK	"vrock"
#define	NAM_HEZROU	"hezrou"
#define	NAM_BONE_DEVIL	"bone devil"
#define	NAM_ICE_DEVIL	"ice devil"
#define	NAM_NALFESHNEE	"nalfeshnee"
#define	NAM_PIT_FIEND	"pit fiend"
#define	NAM_BALROG	"balrog"
#define	NAM_JUIBLEX	"Juiblex"
#define	NAM_YEENOGHU	"Yeenoghu"
#define	NAM_ORCUS	"Orcus"
#define	NAM_GERYON	"Geryon"
#define	NAM_DISPATER	"Dispater"
#define	NAM_BAALZEBUB	"Baalzebub"
#define	NAM_ASMODEUS	"Asmodeus"
#define	NAM_DEMOGORGON	"Demogorgon"
#define	NAM_DEATH	"Death"
#define	NAM_PESTILENCE	"Pestilence"
#define	NAM_FAMINE	"Famine"
#define	NAM_MAIL_DAEMON	"mail daemon"
#define	NAM_DJINNI	"djinni"
#define	NAM_SANDESTIN	"sandestin"
#define	NAM_JELLYFISH	"jellyfish"
#define	NAM_PIRANHA	"piranha"
#define	NAM_SHARK	"shark"
#define	NAM_GIANT_EEL	"giant eel"
#define	NAM_ELECTRIC_EEL	"electric eel"
#define	NAM_KRAKEN	"kraken"
#define	NAM_NEWT	"newt"
#define	NAM_GECKO	"gecko"
#define	NAM_IGUANA	"iguana"
#define	NAM_BABY_CROCODILE	"baby crocodile"
#define	NAM_LIZARD	"lizard"
#define	NAM_CHAMELEON	"chameleon"
#define	NAM_CROCODILE	"crocodile"
#define	NAM_SALAMANDER	"salamander"
#define	NAM_LONG_WORM_TAIL	"long worm tail"
#define	NAM_ARCHEOLOGIST	"archeologist"
#define	NAM_BARBARIAN	"barbarian"
#define	NAM_CAVEMAN	"caveman"
#define	NAM_CAVEWOMAN	"cavewoman"
#define	NAM_HEALER	"healer"
#define	NAM_KNIGHT	"knight"
#define	NAM_MONK	"monk"
#define	NAM_PRIEST	"priest"
#define	NAM_PRIESTESS	"priestess"
#define	NAM_RANGER	"ranger"
#define	NAM_ROGUE	"rogue"
#define	NAM_SAMURAI	"samurai"
#define	NAM_TOURIST	"tourist"
#define	NAM_VALKYRIE	"valkyrie"
#define	NAM_WIZARD	"wizard"
#define	NAM_LORD_CARNARVON	"Lord Carnarvon"
#define	NAM_PELIAS	"Pelias"
#define	NAM_SHAMAN_KARNOV	"Shaman Karnov"
#define	NAM_EARENDIL	"Earendil"
#define	NAM_ELWING	"Elwing"
#define	NAM_HIPPOCRATES	"Hippocrates"
#define	NAM_KING_ARTHUR	"King Arthur"
#define	NAM_GRAND_MASTER	"Grand Master"
#define	NAM_ARCH_PRIEST	"Arch Priest"
#define	NAM_ORION	"Orion"
#define	NAM_MASTER_OF_THIEVES	"Master of Thieves"
#define	NAM_LORD_SATO	"Lord Sato"
#define	NAM_TWOFLOWER	"Twoflower"
#define	NAM_NORN	"Norn"
#define NAM_NEFERET_THE_GREEN	"Neferet the Green"
#define	NAM_MINION_OF_HUHETOTL	"Minion of Huhetotl"
#define	NAM_THOTH_AMON	"Thoth Amon"
#define	NAM_CHROMATIC_DRAGON	"Chromatic Dragon"
#define	NAM_GOBLIN_KING	"Goblin King"
#define	NAM_CYCLOPS	"Cyclops"
#define	NAM_IXOTH	"Ixoth"
#define	NAM_MASTER_KAEN	"Master Kaen"
#define	NAM_NALZOK	"Nalzok"
#define	NAM_SCORPIUS	"Scorpius"
#define	NAM_MASTER_ASSASSIN	"Master Assassin"
#define	NAM_ASHIKAGA_TAKAUJI	"Ashikaga Takauji"
#define	NAM_LORD_SURTUR	"Lord Surtur"
#define	NAM_DARK_ONE	"Dark One"
#define	NAM_STUDENT	"student"
#define	NAM_CHIEFTAIN	"chieftain"
#define	NAM_NEANDERTHAL	"neanderthal"
#define	NAM_HIGH_ELF	"High-elf"
#define	NAM_ATTENDANT	"attendant"
#define	NAM_PAGE	"page"
#define	NAM_ABBOT	"abbot"
#define	NAM_ACOLYTE	"acolyte"
#define	NAM_HUNTER	"hunter"
#define	NAM_THUG	"thug"
#define	NAM_NINJA	"ninja"
#define	NAM_ROSHI	"roshi"
#define	NAM_GUIDE	"guide"
#define	NAM_WARRIOR	"warrior"
#define	NAM_APPRENTICE	"apprentice"
