/* A list of object names in English, from the original objects.c */

/*
 * Rings, unidentified amulets, potions, scrolls, spellbooks, wands, and gems
 * use only the type, material, or color for their descriptions.  For example,
 * a white potion uses only "white" in its string.
 *
 * Each category for which this is true is given a distinct prefix for its
 * name symbol.  For example, the white potion is NAM_POT_WHITE, but the white
 * spellbook is NAM_SPE_WHITE.
 *
 * This distinction is not important in English, but in many languages an
 * adjective changes form according to the "gender" of the noun it modifies.
 * In Spanish, for example, a white potion is _poción blanca_ but a white
 * spellbook is _libro mágico blanco_.  In the Spanish version of this header,
 * then, NAM_POT_WHITE is "blanca" while NAM_SPE_WHITE is "blanco".
 */

/* Strange objects */
#define	NAM_STRANGE_OBJECT	"strange object"

/* Weapons, identified */
#define	NAM_ARROW	"arrow"
#define	NAM_ELVEN_ARROW	"elven arrow"
#define	NAM_ORCISH_ARROW	"orcish arrow"
#define	NAM_SILVER_ARROW	"silver arrow"
#define	NAM_YA	"ya"
#define	NAM_CROSSBOW_BOLT	"crossbow bolt"
#define	NAM_DART	"dart"
#define	NAM_SHURIKEN	"shuriken"
#define	NAM_BOOMERANG	"boomerang"
#define	NAM_SPEAR	"spear"
#define	NAM_ELVEN_SPEAR	"elven spear"
#define	NAM_ORCISH_SPEAR	"orcish spear"
#define	NAM_DWARVISH_SPEAR	"dwarvish spear"
#define	NAM_SILVER_SPEAR	"silver spear"
#define	NAM_JAVELIN	"javelin"
#define	NAM_TRIDENT	"trident"
#define	NAM_DAGGER	"dagger"
#define	NAM_ELVEN_DAGGER	"elven dagger"
#define	NAM_ORCISH_DAGGER	"orcish dagger"
#define	NAM_SILVER_DAGGER	"silver dagger"
#define	NAM_ATHAME	"athame"
#define	NAM_SCALPEL	"scalpel"
#define	NAM_KNIFE	"knife"
#define	NAM_STILETTO	"stiletto"
#define	NAM_WORM_TOOTH	"worm tooth"
#define	NAM_CRYSKNIFE	"crysknife"
#define	NAM_AXE	"axe"
#define	NAM_BATTLE_AXE	"battle-axe"
#define	NAM_SHORT_SWORD	"short sword"
#define	NAM_ELVEN_SHORT_SWORD	"elven short sword"
#define	NAM_ORCISH_SHORT_SWORD	"orcish short sword"
#define	NAM_DWARVISH_SHORT_SWORD	"dwarvish short sword"
#define	NAM_SCIMITAR	"scimitar"
#define	NAM_SILVER_SABER	"silver saber"
#define	NAM_BROADSWORD	"broadsword"
#define	NAM_ELVEN_BROADSWORD	"elven broadsword"
#define	NAM_LONG_SWORD	"long sword"
#define	NAM_TWO_HANDED_SWORD	"two-handed sword"
#define	NAM_KATANA	"katana"
#define	NAM_TSURUGI	"tsurugi"
#define	NAM_RUNESWORD	"runesword"
#define	NAM_PARTISAN	"partisan"
#define	NAM_RANSEUR	"ranseur"
#define	NAM_SPETUM	"spetum"
#define	NAM_GLAIVE	"glaive"
#define	NAM_LANCE	"lance"
#define	NAM_HALBERD	"halberd"
#define	NAM_BARDICHE	"bardiche"
#define	NAM_VOULGE	"voulge"
#define	NAM_DWARVISH_MATTOCK	"dwarvish mattock"
#define	NAM_FAUCHARD	"fauchard"
#define	NAM_GUISARME	"guisarme"
#define	NAM_BILL_GUISARME	"bill-guisarme"
#define	NAM_LUCERN_HAMMER	"lucern hammer"
#define	NAM_BEC_DE_CORBIN	"bec de corbin"
#define	NAM_MACE	"mace"
#define	NAM_MORNING_STAR	"morning star"
#define	NAM_WAR_HAMMER	"war hammer"
#define	NAM_CLUB	"club"
#define	NAM_RUBBER_HOSE	"rubber hose"
#define	NAM_QUARTERSTAFF	"quarterstaff"
#define	NAM_AKLYS	"aklys"
#define	NAM_FLAIL	"flail"
#define	NAM_BULLWHIP	"bullwhip"
#define	NAM_BOW	"bow"
#define	NAM_ELVEN_BOW	"elven bow"
#define	NAM_ORCISH_BOW	"orcish bow"
#define	NAM_YUMI	"yumi"
#define	NAM_SLING	"sling"
#define	NAM_CROSSBOW	"crossbow"

/* Weapons, unidentified */
#define	NAM_RUNED_ARROW	"runed arrow"
#define	NAM_CRUDE_ARROW	"crude arrow"
#define	NAM_BAMBOO_ARROW	"bamboo arrow"
#define	NAM_THROWING_STAR	"throwing star"
#define	NAM_RUNED_SPEAR	"runed spear"
#define	NAM_CRUDE_SPEAR	"crude spear"
#define	NAM_STOUT_SPEAR	"stout spear"
#define	NAM_THROWING_SPEAR	"throwing spear"
#define	NAM_RUNED_DAGGER	"runed dagger"
#define	NAM_CRUDE_DAGGER	"crude dagger"
#define	NAM_DOUBLE_HEADED_AXE	"double-headed axe"
#define	NAM_RUNED_SHORT_SWORD	"runed short sword"
#define	NAM_CRUDE_SHORT_SWORD	"crude short sword"
#define	NAM_BROAD_SHORT_SWORD	"broad short sword"
#define	NAM_CURVED_SWORD	"curved sword"
#define	NAM_RUNED_BROADSWORD	"runed broadsword"
#define	NAM_SAMURAI_SWORD	"samurai sword"
#define	NAM_LONG_SAMURAI_SWORD	"long samurai sword"
#define	NAM_VULGAR_POLEARM	"vulgar polearm"
#define	NAM_HILTED_POLEARM	"hilted polearm"
#define	NAM_FORKED_POLEARM	"forked polearm"
#define	NAM_SINGLE_EDGED_POLEARM	"single-edged polearm"
#define	NAM_ANGLED_POLEAXE	"angled poleaxe"
#define	NAM_LONG_POLEAXE	"long poleaxe"
#define	NAM_POLE_CLEAVER	"pole cleaver"
#define	NAM_BROAD_PICK	"broad pick"
#define	NAM_POLE_SICKLE	"pole sickle"
#define	NAM_PRUNING_HOOK	"pruning hook"
#define	NAM_HOOKED_POLEARM	"hooked polearm"
#define	NAM_PRONGED_POLEARM	"pronged polearm"
#define	NAM_BEAKED_POLEARM	"beaked polearm"
#define	NAM_STAFF	"staff"
#define	NAM_THONGED_CLUB	"thonged club"
#define	NAM_RUNED_BOW	"runed bow"
#define	NAM_CRUDE_BOW	"crude bow"
#define	NAM_LONG_BOW	"long bow"

/* Armor, identified */
#define	NAM_ELVEN_LEATHER_HELM	"elven leather helm"
#define	NAM_ORCISH_HELM	"orcish helm"
#define	NAM_DWARVISH_IRON_HELM	"dwarvish iron helm"
#define	NAM_FEDORA	"fedora"
#define	NAM_CORNUTHAUM	"cornuthaum"
#define	NAM_DUNCE_CAP	"dunce cap"
#define	NAM_DENTED_POT	"dented pot"
#define	NAM_HELMET	"helmet"
#define	NAM_HELM_OF_BRILLIANCE	"helm of brilliance"
#define	NAM_HELM_OF_OPPOSITE_ALIGNMENT	"helm of opposite alignment"
#define	NAM_HELM_OF_TELEPATHY	"helm of telepathy"
#define	NAM_GRAY_DRAGON_SCALE_MAIL	"gray dragon scale mail"
#define	NAM_SILVER_DRAGON_SCALE_MAIL	"silver dragon scale mail"
#define	NAM_SHIMMERING_DRAGON_SCALE_MAIL	"shimmering dragon scale mail"
#define	NAM_RED_DRAGON_SCALE_MAIL	"red dragon scale mail"
#define	NAM_WHITE_DRAGON_SCALE_MAIL	"white dragon scale mail"
#define	NAM_ORANGE_DRAGON_SCALE_MAIL	"orange dragon scale mail"
#define	NAM_BLACK_DRAGON_SCALE_MAIL	"black dragon scale mail"
#define	NAM_BLUE_DRAGON_SCALE_MAIL	"blue dragon scale mail"
#define	NAM_GREEN_DRAGON_SCALE_MAIL	"green dragon scale mail"
#define	NAM_YELLOW_DRAGON_SCALE_MAIL	"yellow dragon scale mail"
#define	NAM_GRAY_DRAGON_SCALES	"gray dragon scales"
#define	NAM_SILVER_DRAGON_SCALES	"silver dragon scales"
#define	NAM_SHIMMERING_DRAGON_SCALES	"shimmering dragon scales"
#define	NAM_RED_DRAGON_SCALES	"red dragon scales"
#define	NAM_WHITE_DRAGON_SCALES	"white dragon scales"
#define	NAM_ORANGE_DRAGON_SCALES	"orange dragon scales"
#define	NAM_BLACK_DRAGON_SCALES	"black dragon scales"
#define	NAM_BLUE_DRAGON_SCALES	"blue dragon scales"
#define	NAM_GREEN_DRAGON_SCALES	"green dragon scales"
#define	NAM_YELLOW_DRAGON_SCALES	"yellow dragon scales"
#define	NAM_PLATE_MAIL	"plate mail"
#define	NAM_CRYSTAL_PLATE_MAIL	"crystal plate mail"
#define	NAM_BRONZE_PLATE_MAIL	"bronze plate mail"
#define	NAM_SPLINT_MAIL	"splint mail"
#define	NAM_BANDED_MAIL	"banded mail"
#define	NAM_DWARVISH_MITHRIL_COAT	"dwarvish mithril-coat"
#define	NAM_ELVEN_MITHRIL_COAT	"elven mithril-coat"
#define	NAM_CHAIN_MAIL	"chain mail"
#define	NAM_ORCISH_CHAIN_MAIL	"orcish chain mail"
#define	NAM_SCALE_MAIL	"scale mail"
#define	NAM_STUDDED_LEATHER_ARMOR	"studded leather armor"
#define	NAM_RING_MAIL	"ring mail"
#define	NAM_ORCISH_RING_MAIL	"orcish ring mail"
#define	NAM_LEATHER_ARMOR	"leather armor"
#define	NAM_LEATHER_JACKET	"leather jacket"
#define	NAM_HAWAIIAN_SHIRT	"Hawaiian shirt"
#define	NAM_T_SHIRT	"T-shirt"
#define	NAM_MUMMY_WRAPPING	"mummy wrapping"
#define	NAM_ELVEN_CLOAK	"elven cloak"
#define	NAM_ORCISH_CLOAK	"orcish cloak"
#define	NAM_DWARVISH_CLOAK	"dwarvish cloak"
#define	NAM_OILSKIN_CLOAK	"oilskin cloak"
#define	NAM_ROBE	"robe"
#define	NAM_ALCHEMY_SMOCK	"alchemy smock"
#define NAM_LEATHER_CLOAK	"leather cloak"
#define	NAM_CLOAK_OF_PROTECTION	"cloak of protection"
#define	NAM_CLOAK_OF_INVISIBILITY	"cloak of invisibility"
#define	NAM_CLOAK_OF_MAGIC_RESISTANCE	"cloak of magic resistance"
#define	NAM_CLOAK_OF_DISPLACEMENT	"cloak of displacement"
#define	NAM_SMALL_SHIELD	"small shield"
#define	NAM_ELVEN_SHIELD	"elven shield"
#define	NAM_URUK_HAI_SHIELD	"Uruk-hai shield"
#define	NAM_ORCISH_SHIELD	"orcish shield"
#define	NAM_LARGE_SHIELD	"large shield"
#define	NAM_DWARVISH_ROUNDSHIELD	"dwarvish roundshield"
#define	NAM_SHIELD_OF_REFLECTION	"shield of reflection"
#define	NAM_LEATHER_GLOVES	"leather gloves"
#define	NAM_GAUNTLETS_OF_FUMBLING	"gauntlets of fumbling"
#define	NAM_GAUNTLETS_OF_POWER	"gauntlets of power"
#define	NAM_GAUNTLETS_OF_DEXTERITY	"gauntlets of dexterity"
#define	NAM_LOW_BOOTS	"low boots"
#define	NAM_IRON_SHOES	"iron shoes"
#define	NAM_HIGH_BOOTS	"high boots"
#define	NAM_SPEED_BOOTS	"speed boots"
#define	NAM_WATER_WALKING_BOOTS	"water walking boots"
#define	NAM_JUMPING_BOOTS	"jumping boots"
#define	NAM_ELVEN_BOOTS	"elven boots"
#define	NAM_KICKING_BOOTS	"kicking boots"
#define	NAM_FUMBLE_BOOTS	"fumble boots"
#define	NAM_LEVITATION_BOOTS	"levitation boots"

/* Armor, unidentified */
#define	NAM_LEATHER_HAT	"leather hat"
#define	NAM_IRON_SKULL_CAP	"iron skull cap"
#define	NAM_HARD_HAT	"hard hat"
#define	NAM_CONICAL_HAT	"conical hat"
#define	NAM_PLUMED_HELMET	"plumed helmet"
#define	NAM_ETCHED_HELMET	"etched helmet"
#define	NAM_CRESTED_HELMET	"crested helmet"
#define	NAM_VISORED_HELMET	"visored helmet"
#define	NAM_CRUDE_CHAIN_MAIL	"crude chain mail"
#define	NAM_CRUDE_RING_MAIL	"crude ring mail"
#define	NAM_FADED_PALL	"faded pall"
#define	NAM_COARSE_MANTELET	"coarse mantelet"
#define	NAM_HOODED_CLOAK	"hooded cloak"
#define	NAM_SLIPPERY_CLOAK	"slippery cloak"
#define	NAM_APRON	"apron"
#define	NAM_TATTERED_CAPE	"tattered cape"
#define	NAM_OPERA_CLOAK	"opera cloak"
#define	NAM_ORNAMENTAL_COPE	"ornamental cope"
#define	NAM_PIECE_OF_CLOTH	"piece of cloth"
#define	NAM_BLUE_AND_GREEN_SHIELD	"blue and green shield"
#define	NAM_WHITE_HANDED_SHIELD	"white-handed shield"
#define	NAM_RED_EYED_SHIELD	"red-eyed shield"
#define	NAM_LARGE_ROUND_SHIELD	"large round shield"
#define	NAM_POLISHED_SILVER_SHIELD	"polished silver shield"
#define	NAM_OLD_GLOVES	"old gloves"
#define	NAM_PADDED_GLOVES	"padded gloves"
#define	NAM_RIDING_GLOVES	"riding gloves"
#define	NAM_FENCING_GLOVES	"fencing gloves"
#define	NAM_WALKING_SHOES	"walking shoes"
#define	NAM_HARD_SHOES	"hard shoes"
#define	NAM_JACKBOOTS	"jackboots"
#define	NAM_COMBAT_BOOTS	"combat boots"
#define	NAM_JUNGLE_BOOTS	"jungle boots"
#define	NAM_HIKING_BOOTS	"hiking boots"
#define	NAM_MUD_BOOTS	"mud boots"
#define	NAM_BUCKLED_BOOTS	"buckled boots"
#define	NAM_RIDING_BOOTS	"riding boots"
#define	NAM_SNOW_BOOTS	"snow boots"

/* Rings, identified */
#define	NAM_RING_ADORNMENT	"adornment"
#define	NAM_RING_GAIN_STRENGTH	"gain strength"
#define	NAM_RING_GAIN_CONSTITUTION	"gain constitution"
#define	NAM_RING_INCREASE_ACCURACY	"increase accuracy"
#define	NAM_RING_INCREASE_DAMAGE	"increase damage"
#define	NAM_RING_PROTECTION	"protection"
#define	NAM_RING_REGENERATION	"regeneration"
#define	NAM_RING_SEARCHING	"searching"
#define	NAM_RING_STEALTH	"stealth"
#define	NAM_RING_SUSTAIN_ABILITY	"sustain ability"
#define	NAM_RING_LEVITATION	"levitation"
#define	NAM_RING_HUNGER	"hunger"
#define	NAM_RING_AGGRAVATE_MONSTER	"aggravate monster"
#define	NAM_RING_CONFLICT	"conflict"
#define	NAM_RING_WARNING	"warning"
#define	NAM_RING_POISON_RESISTANCE	"poison resistance"
#define	NAM_RING_FIRE_RESISTANCE	"fire resistance"
#define	NAM_RING_COLD_RESISTANCE	"cold resistance"
#define	NAM_RING_SHOCK_RESISTANCE	"shock resistance"
#define	NAM_RING_FREE_ACTION	"free action"
#define	NAM_RING_SLOW_DIGESTION	"slow digestion"
#define	NAM_RING_TELEPORTATION	"teleportation"
#define	NAM_RING_TELEPORT_CONTROL	"teleport control"
#define	NAM_RING_POLYMORPH	"polymorph"
#define	NAM_RING_POLYMORPH_CONTROL	"polymorph control"
#define	NAM_RING_INVISIBILITY	"invisibility"
#define	NAM_RING_SEE_INVISIBLE	"see invisible"
#define	NAM_RING_PROTECTION_FROM_SHAPE_CHANGERS	"protection from shape changers"

/* Rings, unidentified */
#define	NAM_RING_WOODEN	"wooden"
#define	NAM_RING_GRANITE "granite"
#define	NAM_RING_OPAL	"opal"
#define	NAM_RING_CLAY	"clay"
#define	NAM_RING_CORAL	"coral"
#define	NAM_RING_BLACK_ONYX	"black onyx"
#define	NAM_RING_MOONSTONE	"moonstone"
#define	NAM_RING_TIGER_EYE	"tiger eye"
#define	NAM_RING_JADE	"jade"
#define	NAM_RING_BRONZE	"bronze"
#define	NAM_RING_AGATE	"agate"
#define	NAM_RING_TOPAZ	"topaz"
#define	NAM_RING_SAPPHIRE	"sapphire"
#define	NAM_RING_RUBY	"ruby"
#define	NAM_RING_DIAMOND	"diamond"
#define	NAM_RING_PEARL	"pearl"
#define	NAM_RING_IRON	"iron"
#define	NAM_RING_BRASS	"brass"
#define	NAM_RING_COPPER	"copper"
#define	NAM_RING_TWISTED	"twisted"
#define	NAM_RING_STEEL	"steel"
#define	NAM_RING_SILVER	"silver"
#define	NAM_RING_GOLD	"gold"
#define	NAM_RING_IVORY	"ivory"
#define	NAM_RING_EMERALD	"emerald"
#define	NAM_RING_WIRE	"wire"
#define	NAM_RING_ENGAGEMENT	"engagement"
#define	NAM_RING_SHINY	"shiny"

/* Amulets, identified */
#define	NAM_AMULET_OF_ESP	"amulet of ESP"
#define	NAM_AMULET_OF_LIFE_SAVING	"amulet of life saving"
#define	NAM_AMULET_OF_STRANGULATION	"amulet of strangulation"
#define	NAM_AMULET_OF_RESTFUL_SLEEP	"amulet of restful sleep"
#define	NAM_AMULET_VERSUS_POISON	"amulet versus poison"
#define	NAM_AMULET_OF_CHANGE	"amulet of change"
#define	NAM_AMULET_OF_UNCHANGING	"amulet of unchanging"
#define	NAM_AMULET_OF_REFLECTION	"amulet of reflection"
#define	NAM_AMULET_OF_MAGICAL_BREATHING	"amulet of magical breathing"
#define	NAM_AMULET_OF_YENDOR	"Amulet of Yendor"
#define	NAM_FAKE_AMULET_OF_YENDOR	"cheap plastic imitation of the Amulet of Yendor"

/* Amulets, unidentified */
#define	NAM_AMULET_CIRCULAR	"circular"
#define	NAM_AMULET_SPHERICAL	"spherical"
#define	NAM_AMULET_OVAL	"oval"
#define	NAM_AMULET_TRIANGULAR	"triangular"
#define	NAM_AMULET_PYRAMIDAL	"pyramidal"
#define	NAM_AMULET_SQUARE	"square"
#define	NAM_AMULET_CONCAVE	"concave"
#define	NAM_AMULET_HEXAGONAL	"hexagonal"
#define	NAM_AMULET_OCTAGONAL	"octagonal"

/* Tools, identified */
#define	NAM_LARGE_BOX	"large box"
#define	NAM_CHEST	"chest"
#define	NAM_ICE_BOX	"ice box"
#define	NAM_SACK	"sack"
#define	NAM_OILSKIN_SACK	"oilskin sack"
#define	NAM_BAG_OF_HOLDING	"bag of holding"
#define	NAM_BAG_OF_TRICKS	"bag of tricks"
#define	NAM_SKELETON_KEY	"skeleton key"
#define	NAM_LOCK_PICK	"lock pick"
#define	NAM_CREDIT_CARD	"credit card"
#define	NAM_TALLOW_CANDLE	"tallow candle"
#define	NAM_WAX_CANDLE	"wax candle"
#define	NAM_BRASS_LANTERN	"brass lantern"
#define	NAM_OIL_LAMP	"oil lamp"
#define	NAM_MAGIC_LAMP	"magic lamp"
#define	NAM_EXPENSIVE_CAMERA	"expensive camera"
#define	NAM_MIRROR	"mirror"
#define	NAM_CRYSTAL_BALL	"crystal ball"
#define	NAM_LENSES	"lenses"
#define	NAM_BLINDFOLD	"blindfold"
#define	NAM_TOWEL	"towel"
#define	NAM_SADDLE	"saddle"
#define	NAM_LEASH	"leash"
#define	NAM_STETHOSCOPE	"stethoscope"
#define	NAM_TINNING_KIT	"tinning kit"
#define	NAM_TIN_OPENER	"tin opener"
#define	NAM_CAN_OF_GREASE	"can of grease"
#define	NAM_FIGURINE	"figurine"
#define	NAM_MAGIC_MARKER	"magic marker"
#define	NAM_LAND_MINE	"land mine"
#define	NAM_BEARTRAP	"beartrap"
#define	NAM_TIN_WHISTLE	"tin whistle"
#define	NAM_MAGIC_WHISTLE	"magic whistle"
#define	NAM_WOODEN_FLUTE	"wooden flute"
#define	NAM_MAGIC_FLUTE	"magic flute"
#define	NAM_TOOLED_HORN	"tooled horn"
#define	NAM_FROST_HORN	"frost horn"
#define	NAM_FIRE_HORN	"fire horn"
#define	NAM_HORN_OF_PLENTY	"horn of plenty"
#define	NAM_WOODEN_HARP	"wooden harp"
#define	NAM_MAGIC_HARP	"magic harp"
#define	NAM_BELL	"bell"
#define	NAM_BUGLE	"bugle"
#define	NAM_LEATHER_DRUM	"leather drum"
#define	NAM_DRUM_OF_EARTHQUAKE	"drum of earthquake"
#define	NAM_PICK_AXE	"pick-axe"
#define	NAM_GRAPPLING_HOOK	"grappling hook"
#define	NAM_UNICORN_HORN	"unicorn horn"
#define	NAM_CANDELABRUM_OF_INVOCATION	"Candelabrum of Invocation"
#define	NAM_BELL_OF_OPENING	"Bell of Opening"

/* Tools, unidentified */
#define	NAM_BAG	"bag"
#define	NAM_KEY	"key"
#define	NAM_CANDLE	"candle"
#define	NAM_LAMP	"lamp"
#define	NAM_LOOKING_GLASS	"looking glass"
#define	NAM_GLASS_ORB	"glass orb"
#define	NAM_WHISTLE	"whistle"
#define	NAM_FLUTE	"flute"
#define	NAM_HORN	"horn"
#define	NAM_HARP	"harp"
#define	NAM_DRUM	"drum"
#define	NAM_IRON_HOOK	"iron hook"
#define	NAM_CANDELABRUM	"candelabrum"
#define	NAM_SILVER_BELL	"silver bell"

/* Food */
/* Food does not have to be identified, except for tins */
#define	NAM_TRIPE_RATION	"tripe ration"
#define	NAM_CORPSE	"corpse"
#define	NAM_EGG	"egg"
#define	NAM_MEATBALL	"meatball"
#define	NAM_MEAT_STICK	"meat stick"
#define	NAM_HUGE_CHUNK_OF_MEAT	"huge chunk of meat"
#define	NAM_MEAT_RING	"meat ring"
#define	NAM_KELP_FROND	"kelp frond"
#define	NAM_EUCALYPTUS_LEAF	"eucalyptus leaf"
#define	NAM_APPLE	"apple"
#define	NAM_ORANGE	"orange"
#define	NAM_PEAR	"pear"
#define	NAM_MELON	"melon"
#define	NAM_BANANA	"banana"
#define	NAM_CARROT	"carrot"
#define	NAM_SPRIG_OF_WOLFSBANE	"sprig of wolfsbane"
#define	NAM_CLOVE_OF_GARLIC	"clove of garlic"
#define	NAM_SLIME_MOLD	"slime mold"
#define	NAM_LUMP_OF_ROYAL_JELLY	"lump of royal jelly"
#define	NAM_CREAM_PIE	"cream pie"
#define	NAM_CANDY_BAR	"candy bar"
#define	NAM_FORTUNE_COOKIE	"fortune cookie"
#define	NAM_PANCAKE	"pancake"
#define	NAM_LEMBAS_WAFER	"lembas wafer"
#define	NAM_CRAM_RATION	"cram ration"
#define	NAM_FOOD_RATION	"food ration"
#define	NAM_K_RATION	"K-ration"
#define	NAM_C_RATION	"C-ration"
#define	NAM_TIN	"tin"

/* Potions, identified */
#define	NAM_POT_GAIN_ABILITY	"gain ability"
#define	NAM_POT_RESTORE_ABILITY	"restore ability"
#define	NAM_POT_CONFUSION	"confusion"
#define	NAM_POT_BLINDNESS	"blindness"
#define	NAM_POT_PARALYSIS	"paralysis"
#define	NAM_POT_SPEED	"speed"
#define	NAM_POT_LEVITATION	"levitation"
#define	NAM_POT_HALLUCINATION	"hallucination"
#define	NAM_POT_INVISIBILITY	"invisibility"
#define	NAM_POT_SEE_INVISIBLE	"see invisible"
#define	NAM_POT_HEALING	"healing"
#define	NAM_POT_EXTRA_HEALING	"extra healing"
#define	NAM_POT_GAIN_LEVEL	"gain level"
#define	NAM_POT_ENLIGHTENMENT	"enlightenment"
#define	NAM_POT_MONSTER_DETECTION	"monster detection"
#define	NAM_POT_OBJECT_DETECTION	"object detection"
#define	NAM_POT_GAIN_ENERGY	"gain energy"
#define	NAM_POT_SLEEPING	"sleeping"
#define	NAM_POT_FULL_HEALING	"full healing"
#define	NAM_POT_POLYMORPH	"polymorph"
#define	NAM_POT_BOOZE	"booze"
#define	NAM_POT_SICKNESS	"sickness"
#define	NAM_POT_FRUIT_JUICE	"fruit juice"
#define	NAM_POT_ACID	"acid"
#define	NAM_POT_OIL	"oil"
#define	NAM_POT_WATER	"water"

/* Potions, unidentified */
#define	NAM_POT_RUBY	"ruby"
#define	NAM_POT_PINK	"pink"
#define	NAM_POT_ORANGE	"orange"
#define	NAM_POT_YELLOW	"yellow"
#define	NAM_POT_EMERALD	"emerald"
#define	NAM_POT_DARK_GREEN	"dark green"
#define	NAM_POT_CYAN	"cyan"
#define	NAM_POT_SKY_BLUE	"sky blue"
#define	NAM_POT_BRILLIANT_BLUE	"brilliant blue"
#define	NAM_POT_MAGENTA	"magenta"
#define	NAM_POT_PURPLE_RED	"purple-red"
#define	NAM_POT_PUCE	"puce"
#define	NAM_POT_MILKY	"milky"
#define	NAM_POT_SWIRLY	"swirly"
#define	NAM_POT_BUBBLY	"bubbly"
#define	NAM_POT_SMOKY	"smoky"
#define	NAM_POT_CLOUDY	"cloudy"
#define	NAM_POT_EFFERVESCENT	"effervescent"
#define	NAM_POT_BLACK	"black"
#define	NAM_POT_GOLDEN	"golden"
#define	NAM_POT_BROWN	"brown"
#define	NAM_POT_FIZZY	"fizzy"
#define	NAM_POT_DARK	"dark"
#define	NAM_POT_WHITE	"white"
#define	NAM_POT_MURKY	"murky"
#define	NAM_POT_CLEAR	"clear"

/* Scrolls, identified */
#define	NAM_SCR_ENCHANT_ARMOR	"enchant armor"
#define	NAM_SCR_DESTROY_ARMOR	"destroy armor"
#define	NAM_SCR_CONFUSE_MONSTER	"confuse monster"
#define	NAM_SCR_SCARE_MONSTER	"scare monster"
#define	NAM_SCR_REMOVE_CURSE	"remove curse"
#define	NAM_SCR_ENCHANT_WEAPON	"enchant weapon"
#define	NAM_SCR_CREATE_MONSTER	"create monster"
#define	NAM_SCR_TAMING	"taming"
#define	NAM_SCR_GENOCIDE	"genocide"
#define	NAM_SCR_LIGHT	"light"
#define	NAM_SCR_TELEPORTATION	"teleportation"
#define	NAM_SCR_GOLD_DETECTION	"gold detection"
#define	NAM_SCR_FOOD_DETECTION	"food detection"
#define	NAM_SCR_IDENTIFY	"identify"
#define	NAM_SCR_MAGIC_MAPPING	"magic mapping"
#define	NAM_SCR_AMNESIA	"amnesia"
#define	NAM_SCR_FIRE	"fire"
#define	NAM_SCR_EARTH	"earth"
#define	NAM_SCR_PUNISHMENT	"punishment"
#define	NAM_SCR_CHARGING	"charging"
#define	NAM_SCR_STINKING_CLOUD	"stinking cloud"
#define	NAM_SCR_MAIL	"mail"
#define	NAM_SCR_BLANK_PAPER	"blank paper"

/* Scrolls, unidentified */
/* It may seem that such names as DAIYEN FOOELS don't need to be translated;
   but there's always the possibility that one or more scroll names may prove
   offensive in some language, and should be changed */
#define	NAM_SCR_ZELGO_MER	"ZELGO MER"
#define	NAM_SCR_JUYED_AWK_YACC	"JUYED AWK YACC"
#define	NAM_SCR_NR_9	"NR 9"
#define	NAM_SCR_XIXAXA_XOXAXA_XUXAXA	"XIXAXA XOXAXA XUXAXA"
#define	NAM_SCR_PRATYAVAYAH	"PRATYAVAYAH"
#define	NAM_SCR_DAIYEN_FOOELS	"DAIYEN FOOELS"
#define	NAM_SCR_LEP_GEX_VEN_ZEA	"LEP GEX VEN ZEA"
#define	NAM_SCR_PRIRUTSENIE	"PRIRUTSENIE"
#define	NAM_SCR_ELBIB_YLOH	"ELBIB YLOH"
#define	NAM_SCR_VERR_YED_HORRE	"VERR YED HORRE"
#define	NAM_SCR_VENZAR_BORGAVVE	"VENZAR BORGAVVE"
#define	NAM_SCR_THARR	"THARR"
#define	NAM_SCR_YUM_YUM	"YUM YUM"
#define	NAM_SCR_KERNOD_WEL	"KERNOD WEL"
#define	NAM_SCR_ELAM_EBOW	"ELAM EBOW"
#define	NAM_SCR_DUAM_XNAHT	"DUAM XNAHT"
#define	NAM_SCR_ANDOVA_BEGARIN	"ANDOVA BEGARIN"
#define	NAM_SCR_KIRJE	"KIRJE"
#define	NAM_SCR_VE_FORBRYDERNE	"VE FORBRYDERNE"
#define	NAM_SCR_HACKEM_MUCHE	"HACKEM MUCHE"
#define	NAM_SCR_VELOX_NEB	"VELOX NEB"
#define	NAM_SCR_FOOBIE_BLETCH	"FOOBIE BLETCH"
#define	NAM_SCR_TEMOV	"TEMOV"
#define	NAM_SCR_GARVEN_DEH	"GARVEN DEH"
#define	NAM_SCR_READ_ME	"READ ME"
#define	NAM_SCR_STAMPED	"stamped"
#define	NAM_SCR_UNLABELED	"unlabeled"

/* Spellbooks, identified */
#define	NAM_SPE_DIG	"dig"
#define	NAM_SPE_MAGIC_MISSILE	"magic missile"
#define	NAM_SPE_FIREBALL	"fireball"
#define	NAM_SPE_CONE_OF_COLD	"cone of cold"
#define	NAM_SPE_SLEEP	"sleep"
#define	NAM_SPE_FINGER_OF_DEATH	"finger of death"
#define	NAM_SPE_LIGHT	"light"
#define	NAM_SPE_DETECT_MONSTERS	"detect monsters"
#define	NAM_SPE_HEALING	"healing"
#define	NAM_SPE_KNOCK	"knock"
#define	NAM_SPE_FORCE_BOLT	"force bolt"
#define	NAM_SPE_CONFUSE_MONSTER	"confuse monster"
#define	NAM_SPE_CURE_BLINDNESS	"cure blindness"
#define	NAM_SPE_DRAIN_LIFE	"drain life"
#define	NAM_SPE_SLOW_MONSTER	"slow monster"
#define	NAM_SPE_WIZARD_LOCK	"wizard lock"
#define	NAM_SPE_CREATE_MONSTER	"create monster"
#define	NAM_SPE_DETECT_FOOD	"detect food"
#define	NAM_SPE_CAUSE_FEAR	"cause fear"
#define	NAM_SPE_CLAIRVOYANCE	"clairvoyance"
#define	NAM_SPE_CURE_SICKNESS	"cure sickness"
#define	NAM_SPE_CHARM_MONSTER	"charm monster"
#define	NAM_SPE_HASTE_SELF	"haste self"
#define	NAM_SPE_DETECT_UNSEEN	"detect unseen"
#define	NAM_SPE_LEVITATION	"levitation"
#define	NAM_SPE_EXTRA_HEALING	"extra healing"
#define	NAM_SPE_RESTORE_ABILITY	"restore ability"
#define	NAM_SPE_INVISIBILITY	"invisibility"
#define	NAM_SPE_DETECT_TREASURE	"detect treasure"
#define	NAM_SPE_REMOVE_CURSE	"remove curse"
#define	NAM_SPE_MAGIC_MAPPING	"magic mapping"
#define	NAM_SPE_IDENTIFY	"identify"
#define	NAM_SPE_TURN_UNDEAD	"turn undead"
#define	NAM_SPE_POLYMORPH	"polymorph"
#define	NAM_SPE_TELEPORT_AWAY	"teleport away"
#define	NAM_SPE_CREATE_FAMILIAR	"create familiar"
#define	NAM_SPE_CANCELLATION	"cancellation"
#define	NAM_SPE_PROTECTION	"protection"
#define	NAM_SPE_JUMPING	"jumping"
#define	NAM_SPE_STONE_TO_FLESH	"stone to flesh"
#define	NAM_SPE_FLAME_SPHERE	"flame sphere"
#define	NAM_SPE_FREEZE_SPHERE	"freeze sphere"
#define	NAM_SPE_BLANK_PAPER	"blank paper"
#define	NAM_SPE_BOOK_OF_THE_DEAD	"Book of the Dead"

/* Spellbooks, unidentified */
#define	NAM_SPE_PARCHMENT	"parchment"
#define	NAM_SPE_VELLUM	"vellum"
#define	NAM_SPE_RAGGED	"ragged"
#define	NAM_SPE_DOG_EARED	"dog eared"
#define	NAM_SPE_MOTTLED	"mottled"
#define	NAM_SPE_STAINED	"stained"
#define	NAM_SPE_CLOTH	"cloth"
#define	NAM_SPE_LEATHER	"leather"
#define	NAM_SPE_WHITE	"white"
#define	NAM_SPE_PINK	"pink"
#define	NAM_SPE_RED	"red"
#define	NAM_SPE_ORANGE	"orange"
#define	NAM_SPE_YELLOW	"yellow"
#define	NAM_SPE_VELVET	"velvet"
#define	NAM_SPE_LIGHT_GREEN	"light green"
#define	NAM_SPE_DARK_GREEN	"dark green"
#define	NAM_SPE_TURQUOISE	"turquoise"
#define	NAM_SPE_CYAN	"cyan"
#define	NAM_SPE_LIGHT_BLUE	"light blue"
#define	NAM_SPE_DARK_BLUE	"dark blue"
#define	NAM_SPE_INDIGO	"indigo"
#define	NAM_SPE_MAGENTA	"magenta"
#define	NAM_SPE_PURPLE	"purple"
#define	NAM_SPE_VIOLET	"violet"
#define	NAM_SPE_TAN	"tan"
#define	NAM_SPE_PLAID	"plaid"
#define	NAM_SPE_LIGHT_BROWN	"light brown"
#define	NAM_SPE_DARK_BROWN	"dark brown"
#define	NAM_SPE_GRAY	"gray"
#define	NAM_SPE_WRINKLED	"wrinkled"
#define	NAM_SPE_DUSTY	"dusty"
#define	NAM_SPE_BRONZE	"bronze"
#define	NAM_SPE_COPPER	"copper"
#define	NAM_SPE_SILVER	"silver"
#define	NAM_SPE_GOLD	"gold"
#define	NAM_SPE_GLITTERING	"glittering"
#define	NAM_SPE_SHINING	"shining"
#define	NAM_SPE_DULL	"dull"
#define	NAM_SPE_THIN	"thin"
#define	NAM_SPE_THICK	"thick"
#define	NAM_SPE_CANVAS	"canvas"
#define	NAM_SPE_HARDCOVER	"hardcover"
#define	NAM_SPE_PLAIN	"plain"
#define	NAM_SPE_PAPYRUS	"papyrus"

/* Wands, identified */
#define	NAM_WAND_LIGHT	"light"
#define	NAM_WAND_SECRET_DOOR_DETECTION	"secret door detection"
#define	NAM_WAND_ENLIGHTENMENT	"enlightenment"
#define	NAM_WAND_CREATE_MONSTER	"create monster"
#define	NAM_WAND_WISHING	"wishing"
#define	NAM_WAND_NOTHING	"nothing"
#define	NAM_WAND_STRIKING	"striking"
#define	NAM_WAND_MAKE_INVISIBLE	"make invisible"
#define	NAM_WAND_SLOW_MONSTER	"slow monster"
#define	NAM_WAND_SPEED_MONSTER	"speed monster"
#define	NAM_WAND_UNDEAD_TURNING	"undead turning"
#define	NAM_WAND_POLYMORPH	"polymorph"
#define	NAM_WAND_CANCELLATION	"cancellation"
#define	NAM_WAND_TELEPORTATION	"teleportation"
#define	NAM_WAND_OPENING	"opening"
#define	NAM_WAND_LOCKING	"locking"
#define	NAM_WAND_PROBING	"probing"
#define	NAM_WAND_DIGGING	"digging"
#define	NAM_WAND_MAGIC_MISSILE	"magic missile"
#define	NAM_WAND_FIRE	"fire"
#define	NAM_WAND_COLD	"cold"
#define	NAM_WAND_SLEEP	"sleep"
#define	NAM_WAND_DEATH	"death"
#define	NAM_WAND_LIGHTNING	"lightning"

/* Wands, unidentified */
#define	NAM_WAND_GLASS	"glass"
#define	NAM_WAND_BALSA	"balsa"
#define	NAM_WAND_CRYSTAL	"crystal"
#define	NAM_WAND_MAPLE	"maple"
#define	NAM_WAND_PINE	"pine"
#define	NAM_WAND_OAK	"oak"
#define	NAM_WAND_EBONY	"ebony"
#define	NAM_WAND_MARBLE	"marble"
#define	NAM_WAND_TIN	"tin"
#define	NAM_WAND_BRASS	"brass"
#define	NAM_WAND_COPPER	"copper"
#define	NAM_WAND_SILVER	"silver"
#define	NAM_WAND_PLATINUM	"platinum"
#define	NAM_WAND_IRIDIUM	"iridium"
#define	NAM_WAND_ZINC	"zinc"
#define	NAM_WAND_ALUMINUM	"aluminum"
#define	NAM_WAND_URANIUM	"uranium"
#define	NAM_WAND_IRON	"iron"
#define	NAM_WAND_STEEL	"steel"
#define	NAM_WAND_HEXAGONAL	"hexagonal"
#define	NAM_WAND_SHORT	"short"
#define	NAM_WAND_RUNED	"runed"
#define	NAM_WAND_LONG	"long"
#define	NAM_WAND_CURVED	"curved"
#define	NAM_WAND_FORKED	"forked"
#define	NAM_WAND_SPIKED	"spiked"
#define	NAM_WAND_JEWELED	"jeweled"

/* Coins */
#define	NAM_GOLD_PIECE	"gold piece"

/* Gems, identified */
#define	NAM_GEM_DILITHIUM_CRYSTAL	"dilithium crystal"
#define	NAM_GEM_DIAMOND	"diamond"
#define	NAM_GEM_RUBY	"ruby"
#define	NAM_GEM_JACINTH	"jacinth"
#define	NAM_GEM_SAPPHIRE	"sapphire"
#define	NAM_GEM_BLACK_OPAL	"black opal"
#define	NAM_GEM_EMERALD	"emerald"
#define	NAM_GEM_TURQUOISE	"turquoise"
#define	NAM_GEM_CITRINE	"citrine"
#define	NAM_GEM_AQUAMARINE	"aquamarine"
#define	NAM_GEM_AMBER	"amber"
#define	NAM_GEM_TOPAZ	"topaz"
#define	NAM_GEM_JET	"jet"
#define	NAM_GEM_OPAL	"opal"
#define	NAM_GEM_CHRYSOBERYL	"chrysoberyl"
#define	NAM_GEM_GARNET	"garnet"
#define	NAM_GEM_AMETHYST	"amethyst"
#define	NAM_GEM_JASPER	"jasper"
#define	NAM_GEM_FLUORITE	"fluorite"
#define	NAM_GEM_OBSIDIAN	"obsidian"
#define	NAM_GEM_AGATE	"agate"
#define	NAM_GEM_JADE	"jade"
#define	NAM_GEM_WHITE_GLASS	"worthless piece of white glass"
#define	NAM_GEM_BLUE_GLASS	"worthless piece of blue glass"
#define	NAM_GEM_RED_GLASS	"worthless piece of red glass"
#define	NAM_GEM_YELLOWISH_BROWN_GLASS	"worthless piece of yellowish brown glass"
#define	NAM_GEM_ORANGE_GLASS	"worthless piece of orange glass"
#define	NAM_GEM_YELLOW_GLASS	"worthless piece of yellow glass"
#define	NAM_GEM_BLACK_GLASS	"worthless piece of black glass"
#define	NAM_GEM_GREEN_GLASS	"worthless piece of green glass"
#define	NAM_GEM_VIOLET_GLASS	"worthless piece of violet glass"
#define	NAM_GEM_LUCKSTONE	"luckstone"
#define	NAM_GEM_LOADSTONE	"loadstone"
#define	NAM_GEM_TOUCHSTONE	"touchstone"
#define	NAM_GEM_FLINT	"flint"
#define	NAM_GEM_ROCK	"rock"

/* Gems, unidentified */
#define	NAM_GEM_WHITE	"white"
#define	NAM_GEM_RED	"red"
#define	NAM_GEM_ORANGE	"orange"
#define	NAM_GEM_BLUE	"blue"
#define	NAM_GEM_BLACK	"black"
#define	NAM_GEM_GREEN	"green"
#define	NAM_GEM_YELLOW	"yellow"
#define	NAM_GEM_YELLOWISH_BROWN	"yellowish brown"
#define	NAM_GEM_VIOLET	"violet"
#define	NAM_GEM_GRAY	"gray"

/* Other objects, identified */
#define	NAM_BOULDER	"boulder"
#define	NAM_STATUE	"statue"
#define	NAM_HEAVY_IRON_BALL	"heavy iron ball"
#define	NAM_IRON_CHAIN	"iron chain"
#define	NAM_BLINDING_VENOM	"blinding venom"

/* Other objects, unidentified */
#define	NAM_SPLASH_OF_VENOM	"splash of venom"
#define	NAM_ACID_VENOM	"acid venom"
